export const dict = {
    en: {
        nav_lang: "EN | ID",
        nav_login: "Login",
        login_title: "Dashboard Login",
        login_email: "Email Address",
        login_pass: "Password",
        login_btn: "Sign In",
        login_google: "Continue with Google",
        login_forgot: "Forgot Password?",
        login_no_acc: "Don't have an account?",
        login_signup: "Sign up",
        signup_title: "Create Account",
        signup_name: "Full Name",
        signup_btn: "Create Account",
        signup_has_acc: "Already have an account?",
        hero_tag: "Web3 Infrastructure",
        hero_title: "Clean & Compliant Digital Asset Settlement Layer",
        hero_sub: "Accept BTC and other crypto, automatically screen risks, and settle in USDT with on-chain proof of clean funds.",
        btn_primary: "Settlement →",
        btn_secondary: "View Live Flow",
        prob_title: "The Challenge with BTC Payments",
        prob_1: "Businesses want to settle in USDT, but customers pay in BTC.",
        prob_2: "Incoming BTC may come from high-risk or flagged wallets, increasing AML exposure.",
        prob_3: "Manual OTC workflows are slow, error-prone, and hard to audit.",
        prob_4: "No automated layer to filter, convert, and settle safely across chains.",
        prob_cta: "See How OXO Fixes This",
        sol_title: "How OXO Settlement Works",
        sol_desc: "Unlock institutional potential with smart tools that streamline workflows, boost compliance, and fuel rapid scale.",
        sol_1_title: "Multi-Asset Acceptance",
        sol_1_desc: "Receive crypto from 20+ chains into OXO staging wallets, not just BTC.",
        sol_2_title: "Risk Screening",
        sol_2_desc: "Automatic risk scoring and wallet flags before any settlement happens.",
        sol_3_title: "Smart Engine",
        sol_3_desc: "Optimized routing across DEXs and bridges for fast BTC→USDT conversion.",
        sol_4_title: "ZK-Proof Clean Settlement",
        sol_4_desc: "On-chain ZK proofs that your settled funds are clean and compliant.",
        flow_title: "Interactive User Flow",
        flow_desc: "Click through the steps to see the automated settlement pipeline in action.",
        flow_1: "Customer sends BTC",
        flow_2: "Deposit Detection",
        flow_3: "Risk Quarantine",
        flow_4: "Smart Swap Engine",
        flow_5: "USDT Settlement",
        flow_6: "On-Chain ZK Proof",
        feat_title: "Execution Engine & Scale",
        feat_sub_1: "Multi-Chain & Liquidity",
        feat_desc_1: "Aggregated liquidity from DEXs and bridges across 20+ chains (EVM & non-EVM), thousands of pairs.",
        feat_sub_2: "Speed & Volume",
        feat_desc_2: "Real-time quotes, execution typically completes in 1–3 minutes with parallel routing. Proven 4+ BTC txs.",
        dash_title: "Real-time Dashboard",
        dash_status_1: "Risk Score: Low. No exposure to flagged wallets.",
        dash_btn: "Request Dashboard Access",
        comp_title: "Compliance-First Crypto Settlement",
        comp_1_title: "Quarantine Mode",
        comp_1_desc: "Isolate risky transactions before they ever reach your main business wallet.",
        comp_2_title: "ZK Proof Report",
        comp_2_desc: "Zero-knowledge proof of clean funds, balancing transparency and privacy.",
        form_title: "Start Your Clean Settlement",
        form_subtitle: "See how easy it is to streamline your settlement and boost your productivity.",
        form_step1: "Business Info",
        form_step2: "Settlement Needs",
        form_step3: "Integration",
        f_name: "Company Name",
        f_web: "Website",
        f_jur: "Jurisdiction",
        f_cp: "Contact Person",
        f_email: "Work Email",
        f_asset: "Preferred Settlement Asset (e.g. USDT)",
        f_size: "Typical Ticket Size (e.g. 0.5-5 BTC)",
        f_vol: "Expected Monthly Volume",
        f_check1: "We need BTC→USDT settlement",
        f_check2: "We accept multi-chain assets",
        f_partner: "Already use a custodian/exchange?",
        f_int: "Preferred Integration (API/Dashboard)",
        f_agree: "I agree to be contacted by OXO for a settlement demo.",
        btn_submit: "Submit Settlement Request",
        btn_submitting: "Submitting...",
        f_secure: "Your data is encrypted. No on-chain txs are executed without your explicit approval.",
        succ_title: "Request Submitted!",
        succ_desc: "Our team will review your details and get back to you shortly.",
        succ_btn: "Submit Another Request",
        found_title: "Built by Industry Experts",
        found_bio: "Reza Gandara, Senior Director of Product at Liminal Custody, ex-VP Product at Indodax, and PhD candidate in cross-chain transaction security. Bridging advanced blockchain research with scalable institutional products.",
        faq_title: "Frequently Asked Questions",
        faq_1_q: "Is OXO a custodial service or settlement layer?",
        faq_1_a: "OXO acts primarily as a non-custodial settlement layer and routing engine, partnering with trusted custodians for holding assets when necessary.",
        faq_2_q: "How do you screen for risky wallets?",
        faq_2_a: "We integrate with top-tier on-chain AML providers to score incoming deposits in real-time before routing them to your destination wallet.",
    },
    id: {
        nav_lang: "ID | EN",
        nav_login: "Masuk",
        login_title: "Masuk Dashboard",
        login_email: "Alamat Email",
        login_pass: "Kata Sandi",
        login_btn: "Masuk",
        login_google: "Lanjutkan dengan Google",
        login_forgot: "Lupa Kata Sandi?",
        login_no_acc: "Belum punya akun?",
        login_signup: "Daftar",
        signup_title: "Buat Akun Baru",
        signup_name: "Nama Lengkap",
        signup_btn: "Daftar Akun",
        signup_has_acc: "Sudah punya akun?",
        hero_tag: "Infrastruktur Web3",
        hero_title: "Lapisan Settlement Aset Digital yang Bersih & Patuh Regulasi",
        hero_sub: "Terima BTC dan kripto lain, screening risiko otomatis, dan settle dalam USDT dengan bukti on-chain bahwa dana Anda bersih.",
        btn_primary: "Settlement →",
        btn_secondary: "Lihat Alur Transaksi",
        prob_title: "Tantangan Pembayaran BTC",
        prob_1: "Bisnis ingin settle dalam USDT, tetapi pelanggan membayar dengan BTC.",
        prob_2: "BTC yang masuk bisa berasal dari wallet berisiko/ter-flag, meningkatkan eksposur AML.",
        prob_3: "Proses OTC manual lambat, rawan error, dan sulit diaudit.",
        prob_4: "Belum ada lapisan otomatis untuk memfilter, mengonversi, dan settle lintas chain dengan aman.",
        prob_cta: "Lihat Solusi OXO",
        sol_title: "Cara Kerja OXO Settlement",
        sol_desc: "Buka potensi institusional dengan alat pintar yang merampingkan alur kerja, meningkatkan kepatuhan, dan mendorong skala bisnis.",
        sol_1_title: "Penerimaan Multi-Aset",
        sol_1_desc: "Terima kripto dari 20+ chain ke staging wallet OXO, bukan hanya BTC.",
        sol_2_title: "Screening Risiko",
        sol_2_desc: "Risk scoring dan penandaan wallet otomatis sebelum settlement dilakukan.",
        sol_3_title: "Engine Eksekusi Pintar",
        sol_3_desc: "Routing optimal lintas DEX dan bridge untuk konversi BTC→USDT yang cepat.",
        sol_4_title: "Settlement Bersih ZK-Proof",
        sol_4_desc: "ZK proof on-chain yang menunjukkan dana settlement Anda bersih dan patuh.",
        flow_title: "Alur Pengguna Interaktif",
        flow_desc: "Klik setiap tahapan untuk melihat jalannya alur otomatisasi settlement.",
        flow_1: "Pelanggan Kirim BTC",
        flow_2: "Deteksi Deposit",
        flow_3: "Karantina Risiko",
        flow_4: "Engine Swap Pintar",
        flow_5: "Settlement USDT",
        flow_6: "Bukti ZK On-Chain",
        feat_title: "Engine Eksekusi & Skala",
        feat_sub_1: "Multi-Chain & Likuiditas",
        feat_desc_1: "Likuiditas teragregasi dari DEX dan bridge di 20+ chain (EVM & non-EVM), ribuan pasangan token.",
        feat_sub_2: "Kecepatan & Volume",
        feat_desc_2: "Quote real-time, eksekusi selesai dalam 1–3 menit. Transaksi 4+ BTC sudah pernah dieksekusi.",
        dash_title: "Dashboard Real-time",
        dash_status_1: "Risk Score: Rendah. Tidak terpapar wallet ter-flag.",
        dash_btn: "Minta Akses Dashboard",
        comp_title: "Settlement Kripto Mengutamakan Kepatuhan",
        comp_1_title: "Mode Karantina",
        comp_1_desc: "Isolasi transaksi berisiko sebelum menyentuh wallet utama bisnis Anda.",
        comp_2_title: "Laporan ZK Proof",
        comp_2_desc: "Zero-knowledge proof atas kebersihan dana, menyeimbangkan transparansi dan privasi.",
        form_title: "Mulai Settlement Bersih Anda",
        form_subtitle: "Lihat betapa mudahnya merampingkan settlement Anda dan meningkatkan produktivitas.",
        form_step1: "Info Bisnis",
        form_step2: "Kebutuhan Settlement",
        form_step3: "Integrasi",
        f_name: "Nama Perusahaan",
        f_web: "Situs Web",
        f_jur: "Negara Operasi",
        f_cp: "Nama Kontak",
        f_email: "Email Kantor",
        f_asset: "Aset Settlement Utama (mis. USDT)",
        f_size: "Kisaran Nilai Transaksi (mis. 0.5-5 BTC)",
        f_vol: "Perkiraan Volume Bulanan",
        f_check1: "Kami butuh settlement BTC→USDT",
        f_check2: "Kami menerima aset dari banyak chain",
        f_partner: "Sudah pakai kustodian/exchange mitra?",
        f_int: "Integrasi yang diinginkan (API/Dashboard)",
        f_agree: "Saya setuju dihubungi OXO untuk demo settlement.",
        btn_submit: "Kirim Permintaan Settlement",
        btn_submitting: "Mengirim...",
        f_secure: "Data Anda dienkripsi. Tidak ada transaksi on-chain dieksekusi tanpa persetujuan Anda.",
        succ_title: "Permintaan Terkirim!",
        succ_desc: "Tim kami akan meninjau detail Anda dan segera menghubungi Anda kembali.",
        succ_btn: "Kirim Permintaan Lainnya",
        found_title: "Dibangun oleh Ahli Industri",
        found_bio: "Reza Gandara, Senior Director of Product di Liminal Custody, eks-VP Product di Indodax, dan kandidat PhD keamanan transaksi cross-chain. Menjembatani riset blockchain dengan produk institusional.",
        faq_title: "Pertanyaan yang Sering Diajukan",
        faq_1_q: "Apakah OXO layanan kustodian atau settlement layer?",
        faq_1_a: "OXO bertindak sebagai lapisan settlement non-kustodian dan engine routing, bermitra dengan kustodian terpercaya untuk menahan aset jika diperlukan.",
        faq_2_q: "Bagaimana cara screening wallet berisiko?",
        faq_2_a: "Kami terintegrasi dengan penyedia AML on-chain papan atas untuk memberikan skor pada deposit masuk secara real-time sebelum diarahkan ke wallet tujuan Anda.",
    },
} as const;

export type Dict = typeof dict.en;
export type Lang = keyof typeof dict;
