export const dict = {
    en: {
        // Nav
        nav_lang: "EN | ID",
        nav_login: "Login",
        nav_home: "Home",
        nav_compliance: "Compliance",
        nav_about: "About",
        nav_contact: "Contact",

        // Auth modal
        login_title: "Dashboard Login",
        login_email: "Email Address",
        login_pass: "Password",
        login_btn: "Sign In",
        login_google: "Continue with Google",
        login_forgot: "Forgot Password?",
        login_no_acc: "Don't have an account?",
        login_signup: "Sign up",
        signup_title: "Create Account",
        signup_name: "Full Name",
        signup_btn: "Create Account",
        signup_has_acc: "Already have an account?",

        // Hero
        hero_tag: "CRYPTO CHECKOUT PAGE",
        hero_title: "Accept crypto.\nGet settled in USDT.",
        hero_sub: "Your customers can pay with Bitcoin and other digital assets.\nOXO routes the transaction and settles the value into USDT to your business wallet.",
        btn_primary: "Get Started →",
        btn_secondary: "See How It Works ↓",

        // Problem
        prob_tag: "The Problem",
        prob_title: "Accepting Bitcoin directly is risky.",
        prob_body_1: "When someone pays you in BTC, you don't know where it's been. It could have touched a fraudster's wallet, a sanctioned address, or a blacklisted exchange. If you accept it — that becomes your legal problem.",
        prob_body_2: "Then you still have to manually convert it to USDT, which is slow and expensive.",
        prob_1: "Funds may come from risky sources",
        prob_2: "You take on legal & compliance risk",
        prob_3: "Manual conversion is slow & costly",
        prob_4: "No audit trail to protect yourself",
        prob_cta: "See how OXO solves this",

        // How It Works
        flow_tag: "How It Works",
        flow_title: "Simple. Automatic. Transparent.",
        flow_desc: "Three steps. Your customer pays, OXO processes the transaction, and your business receives stable settlement in USDT.",
        flow_1_title: "Customer Pays",
        flow_1_desc: "Your customer sends BTC or another supported asset to the checkout address provided by OXO.",
        flow_1_micro: "From their perspective, it's a standard crypto transfer.",
        flow_2_title: "OXO Processes the Payment",
        flow_2_desc: "OXO verifies the incoming payment, checks the transaction source, and routes it through available liquidity to convert the asset into USDT.",
        flow_2_micro: "Executed automatically using the best available route.",
        flow_3_title: "You Receive USDT",
        flow_3_desc: "The final amount is delivered directly to your settlement wallet in USDT Stable and ready to use.",
        flow_3_micro: "A verifiable settlement record is generated for every transaction.",

        // Features
        feat_tag: "Features",
        feat_title: "Everything included.\nNothing to configure.",
        feat_1_title: "Risk Screening",
        feat_1_desc: "Automatic wallet check before every settlement",
        feat_2_title: "Fast Settlement",
        feat_2_desc: "BTC → USDT in 1–3 minutes",
        feat_3_title: "Quarantine Mode",
        feat_3_desc: "Risky funds held separately — never touch your wallet",
        feat_4_title: "ZK Proof Report",
        feat_4_desc: "Cryptographic clean-fund certificate per transaction",
        feat_5_title: "Live Dashboard",
        feat_5_desc: "See every deposit, swap, and settlement in real time",
        feat_6_title: "20+ Blockchains",
        feat_6_desc: "BTC, ETH, USDT, BNB, SOL and more",
        feat_7_title: "No Volume Caps",
        feat_7_desc: "Handle small or large transactions — no daily limits",

        // Compliance
        comp_tag: "Built-in Compliance",
        comp_title: "Compliance built in,\nnot bolted on.",
        comp_body: "Most crypto tools treat compliance as optional. OXO was built from day one so every settlement you receive is clean, documented, and defensible.",
        comp_1_title: "Quarantine Mode",
        comp_1_desc: "Suspicious funds are held in isolation. They never touch your main wallet automatically. You decide what happens next.",
        comp_2_title: "ZK Proof Report",
        comp_2_desc: "Every settlement comes with a cryptographic certificate proving the funds are clean — verifiable by anyone, revealing nothing private.",

        // Form / CTA
        form_title: "Ready to get started?",
        form_subtitle: "Tell us about your business. We'll have your settlement layer live in 24 hours.",
        form_step1: "Business Info",
        form_step2: "Settlement Needs",
        f_name: "Company Name",
        f_web: "Website",
        f_jur: "Country",
        f_cp: "Your Name",
        f_email: "Work Email",
        f_size: "Typical transaction size",
        f_vol: "Monthly volume",
        f_integration: "How do you want to integrate?",
        f_agree: "I'm okay with OXO reaching out to discuss settlement options.",
        btn_submit: "Send Request →",
        btn_submitting: "Sending...",
        f_secure: "No commitment. We'll reply within 1 business day.",
        f_size_opt1: "Under 0.5 BTC",
        f_size_opt2: "0.5 – 2 BTC",
        f_size_opt3: "2 – 10 BTC",
        f_size_opt4: "10 BTC or more",
        f_vol_opt1: "Under $50k/mo",
        f_vol_opt2: "$50k – $200k/mo",
        f_vol_opt3: "$200k – $1M/mo",
        f_vol_opt4: "Over $1M/mo",
        f_int_opt1: "API (developer integration)",
        f_int_opt2: "Dashboard only",
        f_int_opt3: "Both API and Dashboard",

        // Success
        succ_title: "Request Sent!",
        succ_desc: "We'll review your details and get back to you within 1 business day.",
        succ_btn: "Submit Another Request",

        // Founder
        found_title: "Built by Industry Experts",
        found_bio: "Reza Gandara — Senior Director of Product at Liminal Custody, ex-VP Product at Indodax, and PhD candidate in cross-chain security. Built OXO to solve a real problem he saw in crypto payments.",

        // FAQ
        faq_title: "Common questions",
        faq_1_q: "Does my customer need to use OXO?",
        faq_1_a: "No. Your customer simply sends crypto as they normally would.\nOXO operates on the checkout and settlement layer, so the process is invisible to them.",
        faq_2_q: "What if incoming funds are flagged as risky?",
        faq_2_a: "Transactions that fail verification are placed in a quarantine state.\nThey are isolated and will not proceed to settlement until you review or resolve them.\nYour settlement wallet is never automatically exposed to flagged transactions.",
        faq_3_q: "What is a ZK Proof?",
        faq_3_a: "A ZK Proof is a cryptographic verification that confirms a transaction passed OXO's compliance and verification checks.\nIt allows you to demonstrate that funds were verified without exposing sensitive business or transaction details.",
        faq_4_q: "How fast is settlement?",
        faq_4_a: "Settlement usually occurs within 1-3 minutes after the incoming transaction is confirmed on the network.\nThe exact timing depends on the blockchain confirmation speed.",
        faq_5_q: "Is there a volume limit?",
        faq_5_a: "OXO supports both small and large transactions. The system automatically routes transactions through available liquidity to process higher volumes when needed.",
        faq_6_q: "Who is OXO for?",
        faq_6_a: "OXO is built for businesses that want to accept crypto payments but receive stable settlement. Typical users include:\n\n• Merchants\n• Digital platforms\n• Fintech companies\n• Web3 services",

        // Footer
        footer_tagline: "Clean crypto settlement. Zero compliance headache.",
        footer_contact: "Talk to us: developer@oxo.so · oxo.so",
    },

    id: {
        // Nav
        nav_lang: "ID | EN",
        nav_login: "Masuk",
        nav_home: "Beranda",
        nav_compliance: "Kepatuhan",
        nav_about: "Tentang",
        nav_contact: "Kontak",

        // Auth modal
        login_title: "Masuk Dashboard",
        login_email: "Alamat Email",
        login_pass: "Kata Sandi",
        login_btn: "Masuk",
        login_google: "Lanjutkan dengan Google",
        login_forgot: "Lupa Kata Sandi?",
        login_no_acc: "Belum punya akun?",
        login_signup: "Daftar",
        signup_title: "Buat Akun",
        signup_name: "Nama Lengkap",
        signup_btn: "Daftar Akun",
        signup_has_acc: "Sudah punya akun?",

        // Hero
        hero_tag: "HALAMAN CHECKOUT KRIPTO",
        hero_title: "Terima kripto.\nSettle di USDT.",
        hero_sub: "Pelanggan Anda dapat membayar dengan Bitcoin dan aset digital lainnya.\nOXO merutekan transaksi dan menyesuaikan nilainya menjadi USDT ke dompet bisnis Anda.",
        btn_primary: "Mulai Sekarang →",
        btn_secondary: "Lihat Cara Kerjanya ↓",

        // Problem
        prob_tag: "Masalahnya",
        prob_title: "Menerima Bitcoin langsung itu berisiko.",
        prob_body_1: "Saat seseorang bayar pake BTC, Anda nggak tahu Bitcoin itu dari mana. Bisa saja pernah dipakai untuk penipuan, masuk daftar hitam, atau menyentuh alamat yang kena sanksi. Kalau Anda yang terima — masalah itu jadi masalah hukum Anda.",
        prob_body_2: "Belum lagi proses konversi manual ke USDT yang lambat dan mahal.",
        prob_1: "Dana bisa datang dari sumber berisiko",
        prob_2: "Anda menanggung risiko hukum & kepatuhan",
        prob_3: "Konversi manual lambat dan mahal",
        prob_4: "Nggak ada bukti untuk melindungi diri sendiri",
        prob_cta: "Lihat solusi OXO",

        // How It Works
        flow_tag: "Cara Kerja",
        flow_title: "Sederhana. Otomatis. Transparan.",
        flow_desc: "Tiga langkah. Pelanggan Anda membayar, OXO memproses transaksi, dan bisnis Anda menerima pelunasan stabil dalam USDT.",
        flow_1_title: "Pelanggan Membayar",
        flow_1_desc: "Pelanggan Anda mengirim BTC atau aset lain yang didukung ke alamat checkout yang disediakan oleh OXO.",
        flow_1_micro: "Dari perspektif mereka, ini adalah transfer kripto standar.",
        flow_2_title: "OXO Memproses Pembayaran",
        flow_2_desc: "OXO memverifikasi pembayaran masuk, memeriksa sumber transaksi, dan merutekannya melalui likuiditas yang tersedia untuk mengubah aset menjadi USDT.",
        flow_2_micro: "Dieksekusi secara otomatis menggunakan rute terbaik yang tersedia.",
        flow_3_title: "Anda Menerima USDT",
        flow_3_desc: "Jumlah akhir dikirim langsung ke dompet settlement Anda dalam USDT yang stabil dan siap digunakan.",
        flow_3_micro: "Catatan settlement yang dapat diverifikasi dibuat untuk setiap transaksi.",

        // Features
        feat_tag: "Fitur",
        feat_title: "Semua sudah ada.\nTanpa perlu konfigurasi.",
        feat_1_title: "Risk Screening",
        feat_1_desc: "Cek otomatis sebelum setiap settlement",
        feat_2_title: "Settlement Cepat",
        feat_2_desc: "BTC → USDT dalam 1–3 menit",
        feat_3_title: "Quarantine Mode",
        feat_3_desc: "Dana berisiko diisolasi — nggak menyentuh wallet Anda",
        feat_4_title: "Laporan ZK Proof",
        feat_4_desc: "Sertifikat kriptografis dana bersih per transaksi",
        feat_5_title: "Dashboard Live",
        feat_5_desc: "Pantau setiap deposit, swap, dan settlement real-time",
        feat_6_title: "20+ Blockchain",
        feat_6_desc: "BTC, ETH, USDT, BNB, SOL dan banyak lagi",
        feat_7_title: "Tanpa Batas Volume",
        feat_7_desc: "Transaksi kecil atau besar — tanpa batas harian",

        // Compliance
        comp_tag: "Kepatuhan Bawaan",
        comp_title: "Kepatuhan yang tertanam,\nbukan dipaksakan.",
        comp_body: "Kebanyakan alat kripto anggap kepatuhan sebagai opsional. OXO dibangun dari awal supaya setiap settlement yang Anda terima bersih, terdokumentasi, dan bisa dipertanggungjawabkan.",
        comp_1_title: "Quarantine Mode",
        comp_1_desc: "Dana mencurigakan diisolasi. Nggak pernah otomatis masuk ke wallet utama Anda. Anda yang tentukan langkah selanjutnya.",
        comp_2_title: "Laporan ZK Proof",
        comp_2_desc: "Setiap settlement dapat sertifikat kriptografis yang membuktikan dana bersih — bisa diverifikasi siapa saja, tanpa bocorkan data privat Anda.",

        // Form / CTA
        form_title: "Siap memulai?",
        form_subtitle: "Ceritakan bisnis Anda. Kami siapkan settlement layer-nya dalam 24 jam.",
        form_step1: "Info Bisnis",
        form_step2: "Kebutuhan Settlement",
        f_name: "Nama Perusahaan",
        f_web: "Website",
        f_jur: "Negara",
        f_cp: "Nama Anda",
        f_email: "Email Kantor",
        f_size: "Ukuran transaksi biasanya",
        f_vol: "Volume per bulan",
        f_integration: "Mau integrasi bagaimana?",
        f_agree: "Saya setuju dihubungi tim OXO untuk diskusi settlement.",
        btn_submit: "Kirim Permintaan →",
        btn_submitting: "Mengirim...",
        f_secure: "Tidak ada komitmen. Kami balas dalam 1 hari kerja.",
        f_size_opt1: "Di bawah 0.5 BTC",
        f_size_opt2: "0.5 – 2 BTC",
        f_size_opt3: "2 – 10 BTC",
        f_size_opt4: "10 BTC ke atas",
        f_vol_opt1: "Di bawah $50rb/bln",
        f_vol_opt2: "$50rb – $200rb/bln",
        f_vol_opt3: "$200rb – $1 Jt/bln",
        f_vol_opt4: "Di atas $1 Jt/bln",
        f_int_opt1: "API (integrasi developer)",
        f_int_opt2: "Dashboard saja",
        f_int_opt3: "API dan Dashboard",

        // Success
        succ_title: "Permintaan Terkirim!",
        succ_desc: "Kami akan review dan hubungi Anda dalam 1 hari kerja.",
        succ_btn: "Kirim Permintaan Lain",

        // Founder
        found_title: "Dibangun oleh Ahli Industri",
        found_bio: "Reza Gandara — Senior Director of Product di Liminal Custody, eks VP Product Indodax, dan kandidat PhD keamanan cross-chain. OXO dibangun untuk menyelesaikan masalah nyata yang beliau lihat sendiri di industri kripto.",

        // FAQ
        faq_title: "Pertanyaan umum",
        faq_1_q: "Apakah pelanggan saya perlu menggunakan OXO?",
        faq_1_a: "Tidak. Pelanggan Anda cukup mengirim kripto seperti biasanya.\nOXO beroperasi pada lapisan checkout dan settlement, sehingga prosesnya tidak terlihat oleh mereka.",
        faq_2_q: "Bagaimana jika dana yang masuk ditandai sebagai berisiko?",
        faq_2_a: "Transaksi yang gagal verifikasi akan ditempatkan dalam status karantina.\nDana tersebut diisolasi dan tidak akan berlanjut ke settlement sampai Anda meninjau atau menyelesaikannya.\nDompet settlement Anda tidak pernah secara otomatis terpapar pada transaksi yang ditandai.",
        faq_3_q: "Apa itu ZK Proof?",
        faq_3_a: "ZK Proof adalah verifikasi kriptografi yang mengonfirmasi bahwa transaksi telah lolos pemeriksaan kepatuhan dan verifikasi OXO.\nIni memungkinkan Anda untuk menunjukkan bahwa dana telah diverifikasi tanpa mengungkap rincian bisnis atau transaksi yang sensitif.",
        faq_4_q: "Seberapa cepat settlement-nya?",
        faq_4_a: "Settlement biasanya terjadi dalam 1-3 menit setelah transaksi masuk dikonfirmasi di jaringan.\nWaktu tepatnya tergantung pada kecepatan konfirmasi blockchain.",
        faq_5_q: "Apakah ada batas volume?",
        faq_5_a: "OXO mendukung transaksi kecil maupun besar. Sistem secara otomatis merutekan transaksi melalui likuiditas yang tersedia untuk memproses volume yang lebih tinggi saat dibutuhkan.",
        faq_6_q: "OXO untuk siapa?",
        faq_6_a: "OXO dibangun untuk bisnis yang ingin menerima pembayaran kripto tetapi menerima settlement yang stabil. Pengguna tipikal meliputi:\n\n• Merchant\n• Platform digital\n• Perusahaan fintech\n• Layanan Web3",

        // Footer
        footer_tagline: "Settlement kripto yang bersih. Tanpa pusing soal regulasi.",
        footer_contact: "Hubungi kami: developer@oxo.so · oxo.so",
    },
} as const;

export type Dict = typeof dict.en | typeof dict.id;
export type Lang = keyof typeof dict;
