export const dict = {
    en: {
        // Nav
        nav_lang: "EN | ID",
        nav_login: "Login",

        // Auth modal
        login_title: "Dashboard Login",
        login_email: "Email Address",
        login_pass: "Password",
        login_btn: "Sign In",
        login_google: "Continue with Google",
        login_forgot: "Forgot Password?",
        login_no_acc: "Don't have an account?",
        login_signup: "Sign up",
        signup_title: "Create Account",
        signup_name: "Full Name",
        signup_btn: "Create Account",
        signup_has_acc: "Already have an account?",

        // Hero
        hero_tag: "Crypto Settlement Infrastructure",
        hero_title: "Get paid in crypto.\nSettle in clean USDT.\nAutomatically.",
        hero_sub: "Your customers pay you in Bitcoin. You want clean, stable USDT. OXO handles everything in between — screening, swapping, and settling — so you never have to touch risky funds.",
        btn_primary: "Start Clean Settlement →",
        btn_secondary: "See How It Works ↓",

        // Problem
        prob_tag: "The Problem",
        prob_title: "The problem with receiving Bitcoin directly",
        prob_body_1: "When someone pays you in BTC, you have no idea where that Bitcoin has been. It might have touched a hacker's wallet, a blacklisted exchange, or a sanctioned address. If you receive it directly, that becomes your problem — legally and financially.",
        prob_body_2: "On top of that, manually converting BTC to USDT through an OTC desk is slow, expensive, and hard to audit.",
        prob_1: "BTC may come from high-risk wallets",
        prob_2: "Receiving it increases your AML exposure",
        prob_3: "Manual conversion is slow & costly",
        prob_4: "No audit trail = compliance nightmare",
        prob_cta: "See How OXO Fixes This",

        // How It Works
        flow_tag: "How It Works",
        flow_title: "How OXO Settlement Works",
        flow_desc: "Three simple steps. Your customer sends crypto. We screen it, convert it, and deliver clean USDT to your wallet — with proof.",
        flow_1_title: "Accept",
        flow_1_desc: "Your customer sends Bitcoin (or any supported crypto) to your unique OXO deposit address. They don't need a special wallet — it works just like a regular crypto transfer.",
        flow_1_micro: "Supports 20+ blockchain networks. No special setup for your customers.",
        flow_2_title: "Screen",
        flow_2_desc: "Before a single dollar moves, OXO checks where the funds came from. If the source looks risky, those funds are automatically quarantined — they never reach your business wallet. Only clean funds move forward.",
        flow_2_micro: "Think of it like a security scanner at the airport — but for your money.",
        flow_3_title: "Swap",
        flow_3_desc: "OXO's smart routing engine automatically converts your BTC into USDT, finding the best path across 20+ blockchains and hundreds of exchanges. No manual OTC calls. No waiting days.",
        flow_3_micro: "Conversion typically completes in 1–3 minutes.",
        flow_4_title: "Settle",
        flow_4_desc: "Clean USDT lands directly in your business wallet. No middle steps, no touching risky funds. Just stable money, ready to use.",
        flow_4_micro: "",
        flow_5_title: "Prove",
        flow_5_desc: "OXO generates an on-chain ZK-proof report with every settlement. This is your cryptographic certificate that the funds you received were clean — verifiable by anyone, revealing nothing private.",
        flow_5_micro: "Your compliance report. Built into every transaction.",

        // Features
        feat_tag: "Features",
        feat_title: "Everything you need.\nNothing you don't.",
        feat_1_icon: "🔍",
        feat_1_title: "Risk Screening",
        feat_1_desc: "Automatic wallet scoring before any settlement",
        feat_2_icon: "⚡",
        feat_2_title: "1–3 Min Execution",
        feat_2_desc: "Fast swap routing across chains",
        feat_3_icon: "🔒",
        feat_3_title: "Quarantine Mode",
        feat_3_desc: "Risky funds isolated, never touch your wallet",
        feat_4_icon: "🧾",
        feat_4_title: "ZK Proof Report",
        feat_4_desc: "On-chain clean fund certificate per transaction",
        feat_5_icon: "📊",
        feat_5_title: "Live Dashboard",
        feat_5_desc: "Track every deposit, swap, and settlement in real time",
        feat_6_icon: "🌐",
        feat_6_title: "20+ Chains",
        feat_6_desc: "BTC, EVM, non-EVM, L2s, sidechains supported",
        feat_7_icon: "📦",
        feat_7_title: "Large Volume Ready",
        feat_7_desc: "No daily caps, configurable thresholds",

        // Compliance
        comp_tag: "Security & Trust",
        comp_title: "Compliance is baked in,\nnot bolted on.",
        comp_body: "Most crypto payment tools treat compliance as an afterthought. OXO was designed from day one to make sure every settlement you receive can withstand scrutiny — from auditors, regulators, and your own peace of mind.",
        comp_1_title: "Quarantine Mode",
        comp_1_desc: "Risky funds are held separately — they never touch your main business wallet automatically. You decide what happens next.",
        comp_2_title: "ZK Proof Report",
        comp_2_desc: "Every settlement comes with a zero-knowledge proof certificate. Verifiable by anyone, revealing nothing private about your business.",

        // Form / CTA
        form_title: "Ready for clean settlement?",
        form_subtitle: "Tell us about your business. We'll set up your settlement layer within 24 hours.",
        form_step1: "Business Info",
        form_step2: "Settlement Needs",
        f_name: "Company Name / Nama Perusahaan",
        f_web: "Website",
        f_jur: "Country of Operation / Negara Operasi",
        f_cp: "Contact Person / Nama Kontak",
        f_email: "Work Email / Email Kantor",
        f_size: "Typical BTC Transaction Size",
        f_vol: "Monthly Volume Estimate",
        f_integration: "Integration Preference",
        f_agree: "I agree to be contacted by the OXO team for a settlement demo.",
        btn_submit: "Submit Settlement Request →",
        btn_submitting: "Submitting...",
        f_secure: "No commitment required. We'll respond within 1 business day.",
        f_size_opt1: "< 0.5 BTC",
        f_size_opt2: "0.5 – 2 BTC",
        f_size_opt3: "2 – 10 BTC",
        f_size_opt4: "10+ BTC",
        f_vol_opt1: "< $50,000 / mo",
        f_vol_opt2: "$50k – $200k / mo",
        f_vol_opt3: "$200k – $1M / mo",
        f_vol_opt4: "$1M+ / mo",
        f_int_opt1: "API Integration",
        f_int_opt2: "Dashboard Only",
        f_int_opt3: "Both API & Dashboard",

        // Success
        succ_title: "Request Submitted!",
        succ_desc: "Our team will review your details and get back to you within 1 business day.",
        succ_btn: "Submit Another Request",

        // Founder
        found_title: "Built by Industry Experts",
        found_bio: "Reza Gandara, Senior Director of Product at Liminal Custody, ex-VP Product at Indodax, and PhD candidate in cross-chain transaction security. Bridging advanced blockchain research with scalable institutional products.",

        // FAQ
        faq_title: "Questions? Here are the ones we hear most.",
        faq_1_q: "Do my customers need to use OXO too?",
        faq_1_a: "No. They just send BTC (or supported crypto) to your OXO deposit address. It works like any normal crypto payment from their side.",
        faq_2_q: "What happens if incoming funds are flagged as risky?",
        faq_2_a: "They go into Quarantine Mode. They're held separately while you decide how to proceed — they never touch your main business wallet automatically.",
        faq_3_q: "What is a ZK Proof and why do I need it?",
        faq_3_a: "A ZK (Zero-Knowledge) Proof is a mathematical certificate that proves something is true without revealing private details. OXO uses it to prove your settled funds are clean — useful for audits without exposing your business data.",
        faq_4_q: "How fast is settlement?",
        faq_4_a: "Typically 1–3 minutes from deposit confirmation to USDT in your wallet.",
        faq_5_q: "Is there a volume limit?",
        faq_5_a: "No daily volume caps. Thresholds are configurable based on your business needs. We've already processed single transactions of 4+ BTC.",
        faq_6_q: "Who is OXO built for?",
        faq_6_a: "Any business that receives crypto payments and wants to settle in USDT without managing compliance risks manually — including merchants, platforms, exchanges, and fintech companies in APAC and MENA.",

        // Footer
        footer_tagline: "Clean crypto settlement for businesses that take compliance seriously.",
        footer_contact: "Reach us at developer@oxo.so or visit oxo.so",
    },

    id: {
        // Nav
        nav_lang: "ID | EN",
        nav_login: "Masuk",

        // Auth modal
        login_title: "Masuk Dashboard",
        login_email: "Alamat Email",
        login_pass: "Kata Sandi",
        login_btn: "Masuk",
        login_google: "Lanjutkan dengan Google",
        login_forgot: "Lupa Kata Sandi?",
        login_no_acc: "Belum punya akun?",
        login_signup: "Daftar",
        signup_title: "Buat Akun Baru",
        signup_name: "Nama Lengkap",
        signup_btn: "Daftar Akun",
        signup_has_acc: "Sudah punya akun?",

        // Hero
        hero_tag: "Infrastruktur Settlement Kripto",
        hero_title: "Terima bayaran kripto.\nCairkan dalam USDT yang bersih.\nOtomatis.",
        hero_sub: "Pelanggan Anda bayar pakai Bitcoin. Anda ingin USDT yang stabil dan bersih. OXO mengurus semuanya di tengah — screening, konversi, hingga pencairan — sehingga Anda tidak perlu menyentuh dana berisiko sama sekali.",
        btn_primary: "Mulai Settlement Bersih →",
        btn_secondary: "Lihat Cara Kerjanya ↓",

        // Problem
        prob_tag: "Masalahnya",
        prob_title: "Masalah saat menerima Bitcoin langsung",
        prob_body_1: "Ketika seseorang membayar Anda dengan BTC, Anda tidak tahu Bitcoin itu dari mana asalnya. Bisa saja pernah masuk wallet hacker, bursa yang masuk daftar hitam, atau alamat yang terkena sanksi. Kalau Anda terima langsung, itu bisa jadi masalah hukum dan keuangan buat Anda.",
        prob_body_2: "Di atas itu semua, konversi manual BTC ke USDT lewat OTC itu lambat, mahal, dan susah diaudit.",
        prob_1: "BTC bisa datang dari wallet berisiko",
        prob_2: "Menerimanya meningkatkan risiko AML Anda",
        prob_3: "Konversi manual lambat dan mahal",
        prob_4: "Tanpa jejak audit = mimpi buruk kepatuhan",
        prob_cta: "Lihat Solusi OXO",

        // How It Works
        flow_tag: "Cara Kerja",
        flow_title: "Cara Kerja OXO Settlement",
        flow_desc: "Tiga langkah mudah. Pelanggan Anda kirim kripto. Kami screening, konversi, dan kirim USDT bersih ke wallet Anda — lengkap dengan buktinya.",
        flow_1_title: "Terima",
        flow_1_desc: "Pelanggan Anda mengirim Bitcoin (atau kripto lain yang didukung) ke alamat deposit OXO unik milik Anda. Mereka tidak butuh wallet khusus — cara kerjanya seperti transfer kripto biasa.",
        flow_1_micro: "Mendukung 20+ jaringan blockchain. Tidak perlu pengaturan khusus untuk pelanggan Anda.",
        flow_2_title: "Periksa",
        flow_2_desc: "Sebelum satu sen pun bergerak, OXO memeriksa asal dana tersebut. Jika sumbernya terlihat berisiko, dana tersebut otomatis dikarantina — tidak akan pernah sampai ke wallet bisnis Anda. Hanya dana bersih yang dilanjutkan.",
        flow_2_micro: "Bayangkan seperti mesin pemindai keamanan di bandara — tapi untuk uang Anda.",
        flow_3_title: "Konversi",
        flow_3_desc: "Mesin routing cerdas OXO secara otomatis mengonversi BTC Anda menjadi USDT, mencari jalur terbaik di 20+ blockchain dan ratusan bursa. Tidak perlu hubungi OTC manual. Tidak perlu menunggu berhari-hari.",
        flow_3_micro: "Konversi biasanya selesai dalam 1–3 menit.",
        flow_4_title: "Cairkan",
        flow_4_desc: "USDT bersih langsung masuk ke wallet bisnis Anda. Tidak ada langkah perantara, tidak ada kontak dengan dana berisiko. Hanya uang stabil yang siap digunakan.",
        flow_4_micro: "",
        flow_5_title: "Buktikan",
        flow_5_desc: "OXO menghasilkan laporan ZK-proof on-chain di setiap settlement. Ini adalah sertifikat kriptografis Anda bahwa dana yang diterima sudah bersih — bisa diverifikasi oleh siapa saja, tanpa mengungkapkan data pribadi.",
        flow_5_micro: "Laporan kepatuhan Anda. Tertanam di setiap transaksi.",

        // Features
        feat_tag: "Fitur",
        feat_title: "Semua yang Anda butuhkan.\nTanpa hal yang tidak perlu.",
        feat_1_icon: "🔍",
        feat_1_title: "Risk Screening",
        feat_1_desc: "Penilaian risiko wallet otomatis sebelum settlement",
        feat_2_icon: "⚡",
        feat_2_title: "Eksekusi 1–3 Menit",
        feat_2_desc: "Routing swap cepat lintas chain",
        feat_3_icon: "🔒",
        feat_3_title: "Quarantine Mode",
        feat_3_desc: "Dana berisiko diisolasi, tidak menyentuh wallet Anda",
        feat_4_icon: "🧾",
        feat_4_title: "Laporan ZK Proof",
        feat_4_desc: "Sertifikat dana bersih on-chain per transaksi",
        feat_5_icon: "📊",
        feat_5_title: "Dashboard Live",
        feat_5_desc: "Pantau setiap deposit, swap, dan settlement secara real-time",
        feat_6_icon: "🌐",
        feat_6_title: "20+ Chain",
        feat_6_desc: "BTC, EVM, non-EVM, L2, sidechain didukung",
        feat_7_icon: "📦",
        feat_7_title: "Siap Volume Besar",
        feat_7_desc: "Tanpa batas harian, threshold fleksibel",

        // Compliance
        comp_tag: "Keamanan & Kepercayaan",
        comp_title: "Kepatuhan sudah tertanam\ndi dalam sistem.",
        comp_body: "Kebanyakan alat pembayaran kripto menganggap kepatuhan sebagai hal sekunder. OXO dirancang sejak awal untuk memastikan setiap settlement yang Anda terima tahan terhadap pemeriksaan — dari auditor, regulator, maupun ketenangan pikiran Anda sendiri.",
        comp_1_title: "Quarantine Mode",
        comp_1_desc: "Dana berisiko ditahan secara terpisah — tidak akan pernah otomatis menyentuh wallet utama bisnis Anda. Anda yang memutuskan langkah selanjutnya.",
        comp_2_title: "Laporan ZK Proof",
        comp_2_desc: "Setiap settlement dilengkapi sertifikat zero-knowledge proof. Bisa diverifikasi siapa saja, tanpa mengungkapkan data privat bisnis Anda.",

        // Form / CTA
        form_title: "Siap untuk settlement yang bersih?",
        form_subtitle: "Ceritakan tentang bisnis Anda. Kami akan menyiapkan lapisan settlement Anda dalam 24 jam.",
        form_step1: "Info Bisnis",
        form_step2: "Kebutuhan Settlement",
        f_name: "Company Name / Nama Perusahaan",
        f_web: "Website",
        f_jur: "Country of Operation / Negara Operasi",
        f_cp: "Contact Person / Nama Kontak",
        f_email: "Work Email / Email Kantor",
        f_size: "Kisaran Nilai Transaksi BTC",
        f_vol: "Perkiraan Volume Bulanan",
        f_integration: "Preferensi Integrasi",
        f_agree: "Saya setuju dihubungi tim OXO untuk demo settlement.",
        btn_submit: "Kirim Permintaan Settlement →",
        btn_submitting: "Mengirim...",
        f_secure: "Tidak ada komitmen yang diperlukan. Kami akan merespons dalam 1 hari kerja.",
        f_size_opt1: "< 0.5 BTC",
        f_size_opt2: "0.5 – 2 BTC",
        f_size_opt3: "2 – 10 BTC",
        f_size_opt4: "10+ BTC",
        f_vol_opt1: "< $50.000 / bln",
        f_vol_opt2: "$50rb – $200rb / bln",
        f_vol_opt3: "$200rb – $1 Jt / bln",
        f_vol_opt4: "$1 Jt+ / bln",
        f_int_opt1: "Integrasi API",
        f_int_opt2: "Dashboard Saja",
        f_int_opt3: "API & Dashboard",

        // Success
        succ_title: "Permintaan Terkirim!",
        succ_desc: "Tim kami akan meninjau detail Anda dan menghubungi Anda dalam 1 hari kerja.",
        succ_btn: "Kirim Permintaan Lainnya",

        // Founder
        found_title: "Dibangun oleh Ahli Industri",
        found_bio: "Reza Gandara, Senior Director of Product di Liminal Custody, eks-VP Product di Indodax, dan kandidat PhD keamanan transaksi cross-chain. Menjembatani riset blockchain dengan produk institusional.",

        // FAQ
        faq_title: "Pertanyaan? Ini yang paling sering kami terima.",
        faq_1_q: "Apakah pelanggan saya perlu menggunakan OXO juga?",
        faq_1_a: "Tidak. Mereka cukup mengirim BTC (atau kripto yang didukung) ke alamat deposit OXO Anda. Dari sisi mereka, ini seperti pembayaran kripto biasa.",
        faq_2_q: "Apa yang terjadi jika dana masuk ditandai berisiko?",
        faq_2_a: "Dana masuk ke Quarantine Mode. Dana ditahan secara terpisah sementara Anda memutuskan langkah selanjutnya — tidak akan pernah otomatis menyentuh wallet utama bisnis Anda.",
        faq_3_q: "Apa itu ZK Proof dan kenapa saya butuh itu?",
        faq_3_a: "ZK (Zero-Knowledge) Proof adalah sertifikat matematis yang membuktikan sesuatu itu benar tanpa mengungkapkan detail privat. OXO menggunakannya untuk membuktikan bahwa dana settlement Anda bersih — berguna untuk audit tanpa mengekspos data bisnis Anda.",
        faq_4_q: "Seberapa cepat settlement-nya?",
        faq_4_a: "Biasanya 1–3 menit dari konfirmasi deposit hingga USDT masuk ke wallet Anda.",
        faq_5_q: "Apakah ada batas volume?",
        faq_5_a: "Tidak ada batas volume harian. Threshold bisa dikonfigurasi sesuai kebutuhan bisnis Anda. Kami sudah memproses satu transaksi tunggal sebesar 4+ BTC.",
        faq_6_q: "OXO cocok untuk siapa?",
        faq_6_a: "Bisnis apa pun yang menerima pembayaran kripto dan ingin settle dalam USDT tanpa mengelola risiko kepatuhan secara manual — termasuk merchant, platform, bursa, dan perusahaan fintech di APAC dan MENA.",

        // Footer
        footer_tagline: "Settlement kripto bersih untuk bisnis yang serius soal kepatuhan.",
        footer_contact: "Hubungi kami di developer@oxo.so atau kunjungi oxo.so",
    },
} as const;

export type Dict = typeof dict.en;
export type Lang = keyof typeof dict;
